version: '3.7'

services:

  mongodb:
    image: mongo:3.6
    container_name: mongodb_dodgeball
    restart: unless-stopped
    volumes:
      - mongodb-dodegaball-storage:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - dodgeball-network

volumes:
  mongodb-dodegaball-storage:


networks:
  dodgeball-network:
    driver: bridge
