version: '3.7'

services:

  mongodb:
    image: mongo:3.6
    container_name: mongodb_dodgeball
    restart: unless-stopped
    volumes:
      - mongodb-dodegaball-storage:/var/lib/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    networks:
      - dodgeball-network

  dodgeball_web:
    image: tolfx/dodgeball-web:latest
    container_name: dodgeball_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - dodgeball-network

  dodgeball_api:
    image: tolfx/dodgeball-api:latest
    container_name: dodgeball_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - MONGO_HOST=mongodb_dodgeball
      - DEBUG=dodgeball*
    networks:
      - dodgeball-network

  dodgeball_micro_fetchserver:
    image: tolfx/dodgeball-fetchserver:latest
    container_name: dodgeball_micro_fetchserver
    restart: unless-stopped
    environment:
      - MONGO_HOST=mongodb_dodgeball
      - DEBUG=dodgeball*
    networks:
      - dodgeball-network

volumes:
  mongodb-dodegaball-storage:


networks:
  dodgeball-network:
    driver: bridge
